theme: minima
title: "Firesight"
description: "ICC752-1 · Proyecto de Desarrollo de Software"
url: "https://l1tnzo.github.io"
baseurl: "/Documentacion-PDS"
minima:
	skin: dark
header_pages:
	- index.md
	- A1.md
